---
sources:
    - name: meter_source
      interval: 60
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - monasca://http://192.168.10.6:8070/v2.0
