---
sources:
    - name: meter_source
      interval: 3600
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - monasca://http://127.0.0.1:8070/v2.0
